const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"试卷选题",
                        "menuJump":"列表",
                        "tableName":"exampapertopic"
                    }
                ],
                "menu":"试卷选题"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-activity",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告信息",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"视频信息",
                        "menuJump":"列表",
                        "tableName":"shipin"
                    }
                ],
                "menu":"视频信息"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"学习足迹",
                        "menuJump":"列表",
                        "tableName":"xuexizuji"
                    }
                ],
                "menu":"学习足迹"
            }
			,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-rank",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"错题本",
                        "tableName":"examrewrongquestion"
                    },
                    {
						"appFrontIcon":"cuIcon-list",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"试卷列表",
                        "tableName":"exampaper"
                    },
                    {
						"appFrontIcon":"cuIcon-footprint",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"考试记录",
                        "tableName":"examrecord"
                    }
                ],
                "menu":"考试管理"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
